import asyncio
import uuid
from typing import Dict, Any, List
from app.agents import (
    RequirementAgent,
    PlannerAgent,
    DatabaseAgent,
    BackendAgent,
    FrontendAgent,
    ReviewAgent,
    TestingAgent,
    DocumentationAgent,
    DeploymentAgent
)

class AgentRunner:
    def __init__(self):
        self.tasks: Dict[str, Dict[str, Any]] = {}

    def get_task(self, task_id: str) -> Dict[str, Any]:
        return self.tasks.get(task_id)

    def create_task(self, prompt: str, settings: Dict[str, Any]) -> str:
        task_id = str(uuid.uuid4())
        self.tasks[task_id] = {
            "id": task_id,
            "prompt": prompt,
            "settings": settings,
            "status": "pending",
            "current_agent_index": -1,
            "logs": [],
            "files": {},
            "error": None
        }
        return task_id

    async def run_task(self, task_id: str):
        task = self.get_task(task_id)
        if not task:
            return

        task["status"] = "running"
        prompt = task["prompt"]
        settings = task["settings"]
        
        # Instantiate agents in order
        pipeline = [
            RequirementAgent(),
            PlannerAgent(),
            DatabaseAgent(),
            BackendAgent(),
            FrontendAgent(),
            ReviewAgent(),
            TestingAgent(),
            DocumentationAgent(),
            DeploymentAgent()
        ]

        # Initial state passed through pipeline
        state = {
            "user_prompt": prompt,
            "settings": settings,
            "files": {},
            "requirements": "",
            "plan": "",
            "database": "",
            "backend_code": {},
            "frontend_code": {},
            "review": "",
            "tests": "",
            "docs": {}
        }

        def make_logger(agent_name: str):
            def log_callback(msg: str):
                task["logs"].append(msg)
            return log_callback

        try:
            for idx, agent in enumerate(pipeline):
                task["current_agent_index"] = idx
                agent.set_log_callback(make_logger(agent.name))
                
                agent.log(f"Initializing agent...")
                state = await agent.execute(state)
                
                # Sync files generated by agent to task
                task["files"].update(state.get("files", {}))
                
                # Small cooling delay between agents
                await asyncio.sleep(1.0)

            task["status"] = "completed"
            task["current_agent_index"] = len(pipeline)
            task["logs"].append("[System] All agents executed successfully. Full-stack workspace is ready!")
            
        except Exception as e:
            task["status"] = "failed"
            task["error"] = str(e)
            task["logs"].append(f"[System Error] Pipeline execution failed: {str(e)}")
            print(f"Error in runner: {e}")
